// 자동 생성 파일 — 수정하지 말 것.
// `npm run sync:letters` 가 채운다.
// next/image placeholder="blur" 용 저해상도 미리보기.

export const LETTER_BLUR: Record<string, string> = {
  '/letters/2026-08-11_diary_01.90d5f2.webp': 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwAF/8QAHRABAAICAgMAAAAAAAAAAAAAAQIRAAMSIVFh8P/EABQBAQAAAAAAAAAAAAAAAAAAAAH/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwDR4vjKnBlrjHkpyXZULege371j6iMdUAKqIYEJzb//2Q==',
  '/letters/2026-08-12_diary_01.2db8ae.webp': 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgID/8QAIRAAAQQCAAcAAAAAAAAAAAAAAQACBBEDEhQhMTNBYdH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFhEBAQEAAAAAAAAAAAAAAAAAABFB/9oADAMBAAIRAxEAPwBZZFACgro+0WyS5+LM5r5JcDsQL5UfHRbsiynsa7iso2F90/ENhR//2Q==',
}
